from django.urls import path

from .admin_views import (
    AdminLoginMfaView,
    AdminLoginView,
    AdminLogoutView,
    AdminMeView,
    AdminMessageDetailView,
    AdminMessageListView,
    AdminMfaDisableView,
    AdminMfaEnableView,
    AdminMfaSetupView,
    AdminMfaStatusView,
    AdminPasswordChangeView,
    AdminNewsDetailView,
    AdminNewsListCreateView,
    AdminReviewDetailView,
    AdminReviewListCreateView,
    AdminReviewSelectionView,
    AdminReviewSyncView,
    AdminServiceDetailView,
    AdminServiceListCreateView,
    AdminSiteSettingsView,
    AdminUploadView,
    AdminUserDetailView,
    AdminUserListCreateView,
    AdminVehicleDetailView,
    AdminVehicleListCreateView,
    AdminWhyChooseItemDetailView,
    AdminWhyChooseItemListCreateView,
)
from .views import (
    ContactCreateView,
    NewsDetailView,
    NewsListView,
    ReviewCreateView,
    ReviewListView,
    ServiceListView,
    SiteSettingsView,
    VehicleDetailView,
    VehicleListView,
    WhyChooseItemListView,
)

urlpatterns = [
    path('settings/', SiteSettingsView.as_view(), name='site-settings'),
    path('services/', ServiceListView.as_view(), name='service-list'),
    path('why-items/', WhyChooseItemListView.as_view(), name='why-item-list'),
    path('news/', NewsListView.as_view(), name='news-list'),
    path('news/<slug:slug>/', NewsDetailView.as_view(), name='news-detail'),
    path('reviews/', ReviewListView.as_view(), name='review-list'),
    path('reviews/submit/', ReviewCreateView.as_view(), name='review-submit'),
    path('vehicles/', VehicleListView.as_view(), name='vehicle-list'),
    path('vehicles/<slug:slug>/', VehicleDetailView.as_view(), name='vehicle-detail'),
    path('contact/', ContactCreateView.as_view(), name='contact-create'),
    # Administration du site (token requis)
    path('admin/login/', AdminLoginView.as_view(), name='admin-login'),
    path('admin/login/mfa/', AdminLoginMfaView.as_view(), name='admin-login-mfa'),
    path('admin/logout/', AdminLogoutView.as_view(), name='admin-logout'),
    path('admin/me/', AdminMeView.as_view(), name='admin-me'),
    path('admin/mfa/status/', AdminMfaStatusView.as_view(), name='admin-mfa-status'),
    path('admin/mfa/setup/', AdminMfaSetupView.as_view(), name='admin-mfa-setup'),
    path('admin/mfa/enable/', AdminMfaEnableView.as_view(), name='admin-mfa-enable'),
    path('admin/mfa/disable/', AdminMfaDisableView.as_view(), name='admin-mfa-disable'),
    path('admin/users/', AdminUserListCreateView.as_view(), name='admin-user-list'),
    path('admin/users/<int:pk>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('admin/password/', AdminPasswordChangeView.as_view(), name='admin-password-change'),
    path('admin/settings/', AdminSiteSettingsView.as_view(), name='admin-settings'),
    path('admin/upload/', AdminUploadView.as_view(), name='admin-upload'),
    path('admin/news/', AdminNewsListCreateView.as_view(), name='admin-news-list'),
    path('admin/news/<int:pk>/', AdminNewsDetailView.as_view(), name='admin-news-detail'),
    path('admin/reviews/', AdminReviewListCreateView.as_view(), name='admin-review-list'),
    path('admin/reviews/sync/', AdminReviewSyncView.as_view(), name='admin-review-sync'),
    path('admin/reviews/selection/', AdminReviewSelectionView.as_view(), name='admin-review-selection'),
    path('admin/reviews/<int:pk>/', AdminReviewDetailView.as_view(), name='admin-review-detail'),
    path('admin/vehicles/', AdminVehicleListCreateView.as_view(), name='admin-vehicle-list'),
    path('admin/vehicles/<int:pk>/', AdminVehicleDetailView.as_view(), name='admin-vehicle-detail'),
    path('admin/services/', AdminServiceListCreateView.as_view(), name='admin-service-list'),
    path('admin/services/<int:pk>/', AdminServiceDetailView.as_view(), name='admin-service-detail'),
    path('admin/why-items/', AdminWhyChooseItemListCreateView.as_view(), name='admin-why-item-list'),
    path('admin/why-items/<int:pk>/', AdminWhyChooseItemDetailView.as_view(), name='admin-why-item-detail'),
    path('admin/messages/', AdminMessageListView.as_view(), name='admin-message-list'),
    path('admin/messages/<int:pk>/', AdminMessageDetailView.as_view(), name='admin-message-detail'),
]
